name: graph-ml-cu128
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.23.0
  - scikit-learn>=1.2.0
  - networkx>=3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - tqdm>=4.65.0
  - pip
  - pip:
      - wandb>=0.15.0
